services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: survey
      POSTGRES_PASSWORD: strongPASS
      POSTGRES_DB: survey
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U survey -d survey"]
      interval: 5s
      timeout: 5s
      retries: 12
    restart: unless-stopped

  api:
    build: ./apps/api
    env_file: ./apps/api/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    restart: unless-stopped

  web:
    build: ./apps/web
    env_file: ./apps/web/.env
    depends_on:
      - api
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgdata:
