services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: survey
      POSTGRES_PASSWORD: strongPASS
      POSTGRES_DB: survey
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U survey -d survey"]
      interval: 5s
      timeout: 5s
      retries: 12
    restart: unless-stopped
volumes:
  pgdata:
