name: Deploy survey.petly.moscow (GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # PNPM
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Node + кеш
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # Ставим зависимости ТОЛЬКО для фронта (обходим несинхронный lock в apps/api)
      - name: Install deps (web only)
        run: pnpm install --no-frozen-lockfile -F ./apps/web

      # Сборка Next; при output: 'export' этого достаточно — 'out' формируется на этапе build
      - name: Build web
        run: pnpm -F web run build

      # Добавим CNAME, .nojekyll и SPA-fallback в артефакт
      - name: Prepare Pages extras
        run: |
          echo "survey.petly.moscow" > apps/web/out/CNAME
          touch apps/web/out/.nojekyll
          if [ -f apps/web/out/index.html ]; then cp apps/web/out/index.html apps/web/out/404.html; fi

      # Заливаем артефакт для GitHub Pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
