name: Deploy Web (apps/web) to GitHub Pages

on:
  push:
    branches: [ main ]
    # если хочешь триггерить только при изменениях во фронте — раскомментируй
    # paths:
    #   - 'apps/web/**'
    #   - '.github/workflows/deploy-web.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages-web'
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  NEXT_TELEMETRY_DISABLED: '1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: PNPM version
        run: pnpm -v

      # УСТАНОВКА ЗАВИСИМОСТЕЙ ТОЛЬКО ДЛЯ apps/web
      # ВАЖНО: убиваем frozen-lockfile, иначе валится из-за апдейтов в других пакетах (apps/api)
      - name: Install deps (web only, no frozen lockfile)
        run: |
          pnpm install --filter "./apps/web..." --no-frozen-lockfile

      # БИЛД + ЭКСПОРТ СТАТИКИ (ожидается, что в apps/web/package.json есть script build:static)
      - name: Build static web
        run: |
          pnpm --filter "./apps/web" run build:static

      # Кладём статику в /docs, чтобы отдать в Pages
      - name: Prepare /docs
        run: |
          rm -rf docs
          mkdir -p docs
          rsync -a apps/web/out/ docs/
          echo "survey.petly.moscow" > docs/CNAME

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
