name: Build & Publish Web to /docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Можно оставить corepack, если так привычнее
      - name: Enable pnpm via corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.17.0 --activate
      - run: pnpm -v

      # ВАЖНО: не frozen-lockfile + фильтр только по фронту
      - name: Install deps (web only, no frozen lockfile)
        run: pnpm -w --filter ./apps/web... install --no-frozen-lockfile
        # альтернативно, можно просто:
        # run: pnpm install --no-frozen-lockfile

      - name: Build web (static export)
        run: pnpm --dir apps/web run build:static

      - name: Prepare /docs
        run: |
          rm -rf docs
          mkdir -p docs
          cp -a apps/web/out/. docs/
          echo 'survey.petly.moscow' > docs/CNAME

      - name: Commit & push /docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: publish web to /docs"
          file_pattern: docs/**
