name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (web)
        working-directory: apps/web
        run: npm ci --no-audit --no-fund

      - name: Build web (static export via next.config output:export)
        working-directory: apps/web
        run: npx next build

      - name: Prepare /docs (artifact root)
        run: |
          rm -rf docs
          mkdir -p docs
          cp -R apps/web/out/* docs/
          # если нужен CNAME в Pages – раскомментируй и подставь домен
          # echo "survey.petly.moscow" > docs/CNAME

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
